name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.3
  envied: ^0.5.4+1
  equatable: ^2.0.5

  # Network
  dio_nexus: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/src/asset/
  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/color/
    - assets/icons/
    - assets/images/
    - assets/lottie/