name: flutter_architecture_v2
description: "Flutter Architecture Template V2"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Core
  equatable: ^2.0.5
  get_it: ^8.0.0

  # Network
  dio_nexus: ^0.2.2

  # State
  flutter_bloc: ^8.1.6

  # Config
  easy_localization: ^3.0.7

  # Utility
  easy_logger: ^0.0.2
  logger: ^2.4.0
  kartal: ^4.1.0
  google_fonts: ^6.2.1

  # Navigation
  auto_route: ^9.2.2

  # Modules
  widgets:
    path: module/widgets
  gen:
    path: module/gen
  common:
    path: module/common
  core:
    path: module/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  device_preview: ^1.2.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  patrol: ^3.11.1

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
